# Generated by Django 5.2.1 on 2025-07-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("txn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="card",
            field=models.CharField(max_length=255),
        ),
    ]
